"""Phase C — reportlab PDF for the ClinNote Clinical-QA Brief."""
from __future__ import annotations

import io
import re
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)


_INVALID_FILENAME_CHARS = re.compile(r"[^A-Za-z0-9._-]+")


def safe_pdf_filename(seed: str) -> str:
    base = _INVALID_FILENAME_CHARS.sub("-", (seed or "note").strip()).strip("-")
    return f"clinnote-brief-{base[:60] or 'note'}.pdf"


def _styles():
    base = getSampleStyleSheet()
    base.add(ParagraphStyle(name="CnTitle", parent=base["Title"], fontSize=18, leading=22,
                            textColor=colors.HexColor("#1a4d7a")))
    base.add(ParagraphStyle(name="CnSection", parent=base["Heading2"], fontSize=13, leading=16,
                            textColor=colors.HexColor("#1a4d7a"), spaceBefore=12, spaceAfter=4))
    base.add(ParagraphStyle(name="CnBody", parent=base["BodyText"], fontSize=10, leading=14))
    base.add(ParagraphStyle(name="CnQuote", parent=base["BodyText"], fontSize=10, leading=14,
                            leftIndent=12, textColor=colors.HexColor("#555555"), italic=True))
    base.add(ParagraphStyle(name="CnFlag", parent=base["BodyText"], fontSize=10, leading=14,
                            textColor=colors.HexColor("#9c1f1f")))
    return base


def render_clinical_qa_brief_pdf(
    *,
    soap_note: Dict[str, Any],
    transcript: Optional[str],
    voice_signals: Dict[str, List[str]],
    voice_medications: List[str],
    voice_allergies: List[str],
    voice_vitals: Dict[str, Any],
    voice_icd_codes: List[str],
    voice_cpt_codes: List[str],
    missing_meds_in_plan: List[Dict[str, Any]],
    missing_allergies_in_note: List[Dict[str, Any]],
    missing_vitals_in_objective: List[Dict[str, Any]],
    uncoded_icd: List[Dict[str, Any]],
    uncoded_cpt: List[Dict[str, Any]],
    critical_unescalated: List[Dict[str, Any]],
    decision: str,
    talking_points: List[Dict[str, Any]],
    generated_by: str,
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.7 * inch, rightMargin=0.7 * inch,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        title="ClinNote Clinical-QA Brief", author=generated_by,
    )
    s = _styles()
    story: list = []

    story.append(Paragraph("Clinical-QA Brief — ClinNote AI", s["CnTitle"]))
    story.append(Spacer(1, 6))

    meta = [
        ["Note ID", str(soap_note.get("id") or "—")],
        ["Specialty", str(soap_note.get("specialty") or "—")],
        ["Status", str(soap_note.get("status") or "—")],
        ["ICD count", str(len(soap_note.get("icd_codes") or []))],
        ["CPT count", str(len(soap_note.get("cpt_codes") or []))],
        ["Voice decision", decision],
        ["Generated by", generated_by],
    ]
    tbl = Table(meta, colWidths=[1.6 * inch, 4.8 * inch])
    tbl.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e6eef5")),
        ("BOX", (0, 0), (-1, -1), 0.4, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Ambient Voice Transcript (verbatim)", s["CnSection"]))
    story.append(Paragraph(transcript or "<i>No transcript on file.</i>", s["CnQuote"]))

    story.append(Paragraph("Critical Signals Not Escalated", s["CnSection"]))
    if critical_unescalated:
        for c in critical_unescalated:
            story.append(Paragraph(c["note"], s["CnFlag"]))
    else:
        story.append(Paragraph("No unescalated critical signals.", s["CnBody"]))

    story.append(Paragraph("Missing Allergies", s["CnSection"]))
    if missing_allergies_in_note:
        for a in missing_allergies_in_note:
            story.append(Paragraph(a["note"], s["CnFlag"]))
    elif voice_allergies:
        story.append(Paragraph(
            f"Voice allergies on file: {', '.join(voice_allergies)}.", s["CnBody"]))
    else:
        story.append(Paragraph("No allergies surfaced in voice.", s["CnBody"]))

    story.append(Paragraph("Medications Discussed But Missing in Plan", s["CnSection"]))
    if missing_meds_in_plan:
        for m in missing_meds_in_plan:
            story.append(Paragraph(m["note"], s["CnFlag"]))
    elif voice_medications:
        story.append(Paragraph(
            f"Voice medications: {', '.join(voice_medications)}. All present in SOAP plan/subjective.",
            s["CnBody"]))
    else:
        story.append(Paragraph("No medications mentioned in voice.", s["CnBody"]))

    story.append(Paragraph("Vitals Cited But Not in Objective", s["CnSection"]))
    if missing_vitals_in_objective:
        for v in missing_vitals_in_objective:
            story.append(Paragraph(v["note"], s["CnFlag"]))
    elif voice_vitals:
        items = ", ".join(f"{k}={v}" for k, v in voice_vitals.items())
        story.append(Paragraph(f"Voice vitals: {items}. All captured.", s["CnBody"]))
    else:
        story.append(Paragraph("No vitals cited in voice.", s["CnBody"]))

    story.append(Paragraph("ICD Coding Gaps", s["CnSection"]))
    if uncoded_icd:
        for u in uncoded_icd:
            story.append(Paragraph(u["note"], s["CnFlag"]))
    elif voice_icd_codes:
        story.append(Paragraph(
            f"Voice references ICD codes {', '.join(voice_icd_codes)} — all present.",
            s["CnBody"]))
    else:
        story.append(Paragraph("No ICD-10 codes cited in voice.", s["CnBody"]))

    story.append(Paragraph("CPT Coding Gaps", s["CnSection"]))
    if uncoded_cpt:
        for u in uncoded_cpt:
            story.append(Paragraph(u["note"], s["CnFlag"]))
    elif voice_cpt_codes:
        story.append(Paragraph(
            f"Voice references CPT codes {', '.join(voice_cpt_codes)} — all present.",
            s["CnBody"]))
    else:
        story.append(Paragraph("No CPT codes cited in voice.", s["CnBody"]))

    story.append(Paragraph("Voice Signal Summary", s["CnSection"]))
    if voice_signals:
        rows = [["Signal", "Evidence excerpt"]]
        for k, ev in voice_signals.items():
            rows.append([k.replace("_", " "), (ev[0] if ev else "")[:80]])
        st = Table(rows, colWidths=[2.0 * inch, 4.4 * inch])
        st.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, -1), "Helvetica", 8),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e6eef5")),
            ("BOX", (0, 0), (-1, -1), 0.4, colors.grey),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(st)
    else:
        story.append(Paragraph("No voice signals detected.", s["CnBody"]))

    story.append(PageBreak())
    story.append(Paragraph("Physician Sign-Off Talking Points", s["CnSection"]))
    if talking_points:
        for tp in talking_points:
            story.append(Paragraph(
                f"<b>[{tp.get('topic','general').replace('_',' ')} • {tp.get('severity','info')}]</b> "
                + tp.get("point", ""),
                s["CnBody"],
            ))
    else:
        story.append(Paragraph("No talking points generated.", s["CnBody"]))

    doc.build(story)
    return buf.getvalue()
